Run commands manually

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -48,64 +48,67 @@ script:
  - sudo ${TRAVIS_PYTHON} -m pip install toml
  - sudo ${TRAVIS_PYTHON} -m pip install Cython==0.29 --install-option="--no-cython-compile"
  - ./contrib/get-antlr-3.4
- - |
-   echo "travis_fold:start:load_script"
-   normal="$(echo -e '\033[0m')" red="$normal$(echo -e '\033[01;31m')" green="$normal$(echo -e '\033[01;32m')"
-   configureCVC4() {
-     echo "CVC4 config - $TRAVIS_CVC4_CONFIG";
-     ./configure.sh --name=build --prefix=$(pwd)/build/install --unit-testing $TRAVIS_CVC4_CONFIG
-   }
-   error() {
-     echo;
-     echo "${red}${1}${normal}";
-     echo;
-     exit 1;
-   }
-   makeCheck() {
-     (
-       cd build
-       make -j2 check ARGS='-LE regress[1-4]' CVC4_REGRESSION_ARGS='--no-early-exit' || error "BUILD/UNIT/SYSTEM/REGRESSION TEST FAILED"
-     )
-   }
-   makeExamples() {
-     (
-       cd examples
-       mkdir build
-       cd build
-       cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../../build/install/lib/cmake
-       make -j2
-       ctest -j2 --output-on-failure || error "RUNNING EXAMPLES FAILED"
-     )
-   }
-   makeInstallCheck() {
-     (
-       cd build
-       make install -j2
-       echo -e "#include <cvc4/cvc4.h>\nint main() { CVC4::ExprManager em; return 0; }" > /tmp/test.cpp
-       $CXX -std=c++11 /tmp/test.cpp -I install/include -L install/lib -lcvc4 -lcln || exit 1
-       # set PYTHONPATH to include the directory containing pycvc4 module
-       export PYTHONPATH=$PYTHONPATH:$(dirname $(find ./install/ -name "pycvc4" -type d))
-       if [[ "$TRAVIS_CVC4_PYTHON_BINDINGS" == "yes" ]]; then
-           $TRAVIS_PYTHON -c "import pycvc4" || exit 1
-       fi
-     )
-   }
-   run() {
-     echo "travis_fold:start:$1"
-     echo "Running $1"
-     $1 || exit 1
-     echo "travis_fold:end:$1"
-   }
-   [[ "$TRAVIS_CVC4_CONFIG" == *"symfpu"* ]] && CVC4_SYMFPU_BUILD="yes"
-   [ -n "$CVC4_SYMFPU_BUILD" ] && run contrib/get-symfpu
-   [ -n "$TRAVIS_CVC4" ] && [ -n "$TRAVIS_WITH_LFSC" ] && run contrib/get-lfsc-checker
-   [ -n "$TRAVIS_CVC4" ] && run configureCVC4
-   [ -n "$TRAVIS_CVC4" ] && run makeCheck
-   [ -z "$CVC4_SYMFPU_BUILD" ] && run makeInstallCheck && run makeExamples
-   [ -z "$TRAVIS_CVC4" ] && error "Unknown Travis-CI configuration"
-   echo "travis_fold:end:load_script"
- - echo; echo "${green}EVERYTHING SEEMED TO PASS!${normal}"
- - ccache -s
+ - ./configure.sh --python-bindings --python3
+ - cd build && make -j2
+ - PYTHONPATH=$PYTHONPATH:`pwd`/src/api/python/ python3 -c "import pycvc4" || exit 1
+ # - |
+ #   echo "travis_fold:start:load_script"
+ #   normal="$(echo -e '\033[0m')" red="$normal$(echo -e '\033[01;31m')" green="$normal$(echo -e '\033[01;32m')"
+ #   configureCVC4() {
+ #     echo "CVC4 config - $TRAVIS_CVC4_CONFIG";
+ #     ./configure.sh --name=build --prefix=$(pwd)/build/install --unit-testing $TRAVIS_CVC4_CONFIG
+ #   }
+ #   error() {
+ #     echo;
+ #     echo "${red}${1}${normal}";
+ #     echo;
+ #     exit 1;
+ #   }
+ #   makeCheck() {
+ #     (
+ #       cd build
+ #       make -j2 check ARGS='-LE regress[1-4]' CVC4_REGRESSION_ARGS='--no-early-exit' || error "BUILD/UNIT/SYSTEM/REGRESSION TEST FAILED"
+ #     )
+ #   }
+ #   makeExamples() {
+ #     (
+ #       cd examples
+ #       mkdir build
+ #       cd build
+ #       cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../../build/install/lib/cmake
+ #       make -j2
+ #       ctest -j2 --output-on-failure || error "RUNNING EXAMPLES FAILED"
+ #     )
+ #   }
+ #   makeInstallCheck() {
+ #     (
+ #       cd build
+ #       make install -j2
+ #       echo -e "#include <cvc4/cvc4.h>\nint main() { CVC4::ExprManager em; return 0; }" > /tmp/test.cpp
+ #       $CXX -std=c++11 /tmp/test.cpp -I install/include -L install/lib -lcvc4 -lcln || exit 1
+ #       # set PYTHONPATH to include the directory containing pycvc4 module
+ #       export PYTHONPATH=$PYTHONPATH:$(dirname $(find ./install/ -name "pycvc4" -type d))
+ #       if [[ "$TRAVIS_CVC4_PYTHON_BINDINGS" == "yes" ]]; then
+ #           $TRAVIS_PYTHON -c "import pycvc4" || exit 1
+ #       fi
+ #     )
+ #   }
+ #   run() {
+ #     echo "travis_fold:start:$1"
+ #     echo "Running $1"
+ #     $1 || exit 1
+ #     echo "travis_fold:end:$1"
+ #   }
+ #   [[ "$TRAVIS_CVC4_CONFIG" == *"symfpu"* ]] && CVC4_SYMFPU_BUILD="yes"
+ #   [ -n "$CVC4_SYMFPU_BUILD" ] && run contrib/get-symfpu
+ #   [ -n "$TRAVIS_CVC4" ] && [ -n "$TRAVIS_WITH_LFSC" ] && run contrib/get-lfsc-checker
+ #   [ -n "$TRAVIS_CVC4" ] && run configureCVC4
+ #   [ -n "$TRAVIS_CVC4" ] && run makeCheck
+ #   [ -z "$CVC4_SYMFPU_BUILD" ] && run makeInstallCheck && run makeExamples
+ #   [ -z "$TRAVIS_CVC4" ] && error "Unknown Travis-CI configuration"
+ #   echo "travis_fold:end:load_script"
+ # - echo; echo "${green}EVERYTHING SEEMED TO PASS!${normal}"
+ # - ccache -s
 matrix:
   fast_finish: true
   include:
